AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template Three Tier Architecture with High Availability: Sample template showing how to create a VPC, NACL,Internet Gateway, Routables, Subnets, Launch Template, Target Groups, Application Load Balancer, Security Groups, Keypair, NAT Gateways, and Auto Scaling Group.**WARNING** This template creates an Amazon EC2, RDS, and ALB. You will be billed for the AWS resources used if you create a stack from this template."

Parameters:
  EnvirinmentName:
    Description:
    Type: String
    Default: Development
      - Development
      - UAT
      - Production
  VPCCidr:
    Description:
    Type:
    Default: 10.1.0.0/16
  PublicSubnetACidr:
    Description:
    Type:
    Default: 10.1.0.0/27
  PublicSubnetBCidr:
    Description:
    Type:
    Default: 10.1.0.32/27
  PrivateSubnetCCidr:
    Description:
    Type:
    Default: 10.1.0.64/27
  PrivateSubnetDCidr:
    Description:
    Type:
    Default: 10.1.0.96/27
  PrivateSubnetECidr:
    Description:
    Type:
    Default: 10.1.0.128/27
  PrivateSubnetFCidr:
    Description:
    Type:
    Default: 10.1.0.160/27
  
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags: 
      - Key: Name
        Value: !Join ['-', [!Ref "AWS::StackName", "vpc"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}


  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value:  !Join ['-',[!Ref "AWS::StackName", "igw"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  
  VPCNetworkACLRules:
    Type: AWS::EC2::NetworkAcl
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Join ['-',[!Ref "AWS::StackName", "nacl"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}


  NACLInboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 32768
        To: 65535
      RuleNumber: 105
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80
  NACLOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
  
  PublicSubnetANACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref PublicSubnetA
  
  PublicSubnetBNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref PublicSubnetB

  PrivateSubnetCNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref PrivateSubnetC
  
  PrivateSubnetDNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref PrivateSubnetD
  
  PrivateSubnetENACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref PrivateSubnetE
  
  PrivateSubnetFNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref PrivateSubnetF
 
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetACidr
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-websubnet01
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetBCidr
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-websubnet02
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}

  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCCidr 
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-appsubnet01
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
  
  PrivateSubnetD:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetDCidr
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-appsubnet02
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
  
  PrivateSubnetE:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetECidr
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-dbsubnet01
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
  
  PrivateSubnetF:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetFCidr
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-dbsubnet02
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Join ["-", [!Ref "AWS::StackName","publicrtb"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
  
  PublicRouteTableTules:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  
  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Join ["-",[!Ref "AWS::StackName","privatertb"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: nuagecloudproject
      - Key: Name
        Value: !Sub ${EnvironmentName}
 
  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref PrivateRouteTable
  
  PublicSubnetDRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetD
      RouteTableId: !Ref PrivateRouteTable
  
  PublicSubnetERouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetE
      RouteTableId: !Ref PrivateRouteTable
  
  PublicSubnetFRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetF
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  VpcId:
    Description: "Id of NUAGE Virtual Private Cloud."
    Value: !Ref VPC
