AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template Three Tier Architecture with High Availability: Sample template showing how to create a VPC, NACL,Internet Gateway, Routables, and Subnets, You will be billed for the AWS resources used if you create a stack from this template."
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
  VPCCidr:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.1.0.0/16
  WebSubnetAz1ACidr:  
    Description: Please enter the IP range (CIDR notation) for the public subnet A in the Availability Zone -1a
    Type: String
    Default: 10.1.0.0/27
  WebSubnetAz1BCidr: 
    Description: Please enter the IP range (CIDR notation) for the public subnet B in the first Availability Zone 1a
    Type: String
    Default: 10.1.0.32/27
  AppSubnetAz1ACidr: 
    Description: Please enter the IP range (CIDR notation) for the private subnet C in the Availability Zone -1a
    Type: String
    Default: 10.1.0.64/27
  AppSubnetAz1BCidr:
    Description: Please enter the IP range (CIDR notation) for the private subnet D in the Availability Zone -1b
    Type: String
    Default: 10.1.0.96/27
  DBSubnetAz1ACidr:
    Description: Please enter the IP range (CIDR notation) for the private subnet E in the Availability Zone -1a
    Type: String
    Default: 10.1.0.128/27
  DBSubnetAz1BCidr:
    Description: Please enter the IP range (CIDR notation) for the private subnet F in the Availability Zone -1b
    Type: String
    Default: 10.1.0.160/27
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags: 
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName",!Ref "EnvironmentName","01vpc01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value:  !Join ["",[!Ref "AWS::StackName", !Ref "EnvironmentName", "01igw01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  WebSubnetAz1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref WebSubnetAz1ACidr
      AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01websnet01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ['-', [!Ref "AWS::StackName", !Ref "EnvironmentName"]]

  WebSubnetAz1B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref WebSubnetAz1BCidr
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01websnet02"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]

  AppSubnetAz1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref AppSubnetAz1ACidr 
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01appsnet01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ['-', [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  
  AppSubnetAz1B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref AppSubnetAz1BCidr
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01appsnet02"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  
  DBSubnetAz1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref DBSubnetAz1ACidr
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01dbsnet01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  
  DBSubnetAz1B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref DBSubnetAz1BCidr
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01dbsnet02"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01pubrtb01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
  
  PublicRouteTableTules:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  
  WebSubnetAz1ARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WebSubnetAz1A
      RouteTableId: !Ref PublicRouteTable
  
  WebSubnetAz1BRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WebSubnetAz1B
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName","01prirtb01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]
 
  AppSubnetAz1ARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnetAz1A
      RouteTableId: !Ref PrivateRouteTable
  
  AppSubnetAz1BRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnetAz1B
      RouteTableId: !Ref PrivateRouteTable
  
  DBSubnetAz1ARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DBSubnetAz1A
      RouteTableId: !Ref PrivateRouteTable
  
  DBSubnetAz1BRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DBSubnetAz1B
      RouteTableId: !Ref PrivateRouteTable

  VPCNetworkACLRules:
    Type: AWS::EC2::NetworkAcl
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Join ["",[!Ref "AWS::StackName", !Ref "EnvironmentName", "01nacl01"]]
      - Key: Owner
        Value: nuageadmin@nuage.com
      - Key: Project
        Value: livonlin
      - Key: Environment
        Value: !Join ["", [!Ref "AWS::StackName", !Ref "EnvironmentName"]]

  NACLInboundEphemeralPortsRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 32768
        To: 65535
  NACLInboundSSHRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 105
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 22
        To: 22
  NACLInboundHTTPRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 110
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80
  NACLInboundHTTPSRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 115
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 443
        To: 443
  NACLInboundMySQLRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 120
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 3306
        To: 3306
  NACLOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
  
  WebSubnetAz1ANACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref WebSubnetAz1A
  
  WebSubnetAz1BNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref WebSubnetAz1B

  AppSubnetAz1ANACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref AppSubnetAz1A
  
  AppSubnetAz1BNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref AppSubnetAz1B
  
  DBSubnetAz1ANACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref DBSubnetAz1A
  
  DBSubnetAz1BNACLAssociattion:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref VPCNetworkACLRules
      SubnetId: !Ref DBSubnetAz1B
 
Outputs:
  VpcId:
    Description: "Id of LivOnlin Virtual Private Cloud."
    Value: !Ref VPC
  WebSubnetAId:
    Description: PublicSubnetA has been created with CIDR 10.1.0.0/27.
    Value: !Ref WebSubnetAz1A
  WebSubnetBId:
    Description: PublicSubnetB has been created with CIDR 10.1.0.32/27.
    Value: !Ref WebSubnetAz1B
  AppSubnetAId:
    Description: AppSubnetAz1A has been created with CIDR 10.1.0.64/27.
    Value: !Ref AppSubnetAz1A
  AppSubnetBId:
    Description: AppSubnetAz1B has been created with CIDR 10.1.0.96/27.
    Value: !Ref AppSubnetAz1B 
  DBSubnetAId:
    Description: DBSubnetAz1A has been created with CIDR 10.1.0.128/27.
    Value: !Ref DBSubnetAz1A
  DBSubnetBId:
    Description: AppSubnetAz1B has been created with CIDR 10.1.0.160/27.
    Value: !Ref AppSubnetAz1B
  InternetGatewayId:
    Description: Internetgateway has been created for vpc.
    Value: !Ref InternetGateway
  PublicRouteTableId:
    Description: Route table has been created for vpc.
    Value: !Ref PublicRouteTable
  VPCNetworkACLRules: 
    Description: Network access control list has been created for vpc.
    Value: !Ref VPCNetworkACLRules
