AWSTemplateFormatVersion: 2010-09-09
Description: 'This is cloudformation template will create stack for RDS resources using existing vpc and subnets.'
Parameters:
  VpcId:
    Description: "Name of an existing vpc ids, Select preferred vpc id for as your requirements."
    Type: List<AWS::EC2::VPC::Id>
    ConstraintDescription: "Must be an existing vpc ids lists."
  SubnetId:
    Description: "Name of an existing subnet ids, Select preferred subnet ids for your database subnets."
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: "Must be an existing subnet ids lists."
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small
      Engine: MySQL
      EngineVersion: 5.7.25
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
